services:
  configSrv:
    container_name: configSrv
    image: dh-mirror.gitverse.ru/mongo:latest    
    ports:
      - "27017:27017"
    volumes:
      - config-data:/data/db
    command:
      [
        "--configsvr", 
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ] 

  shard1-1:
    container_name: shard1-1
    image: dh-mirror.gitverse.ru/mongo:latest    
    ports:
      - "27018:27018"
    volumes:
      - shard1:/data/db
    command:
      [
        "--shardsvr", 
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27018"
      ] 

  shard2-1:
    container_name: shard2-1
    image: dh-mirror.gitverse.ru/mongo:latest    
    ports:
      - "27019:27018"
    volumes:
      - shard2:/data/db
    command:
      [
        "--shardsvr", 
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27018"
      ] 

  router:
    image: dh-mirror.gitverse.ru/mongo:latest    
    container_name: router
    ports:
      - "27020:27017"    
    command:
      [
        "mongos", 
        "-configdb", 
        "config_server/configSrv:27017",
        "--bind_ip_all",
        "--port",
        "27017"
      ]


  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - configSrv
      - router
      - shard1-1
      - shard2-1
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://router"
      MONGODB_DATABASE_NAME: "somedb"
     

volumes:
  config-data:
  shard1:
  shard2:  