services:
  configSrv:
    container_name: configSrv
    image: dh-mirror.gitverse.ru/mongo:latest    
    ports:
      - "27017:27017"
    volumes:
      - config-data:/data/db
    command:
      [
        "--configsvr", 
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ] 

  shard1-1:
    container_name: shard1-1
    image: dh-mirror.gitverse.ru/mongo:latest    
    ports:
      - "27018:27018"
    volumes:
      - shard1-1:/data/db
    command:
      [
        "--shardsvr", 
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27018"
      ] 

  shard1-2:
    container_name: shard1-2
    image: dh-mirror.gitverse.ru/mongo:latest    
    ports:
      - "27021:27018"
    volumes:
      - shard1-2:/data/db
    command:
      [
        "--shardsvr", 
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27018"
      ] 
  shard1-3:
    container_name: shard1-3
    image: dh-mirror.gitverse.ru/mongo:latest    
    ports:
      - "27022:27018"
    volumes:
      - shard1-3:/data/db
    command:
      [
        "--shardsvr", 
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27018"
      ] 

  shard2-1:
    container_name: shard2-1
    image: dh-mirror.gitverse.ru/mongo:latest    
    ports:
      - "27019:27018"
    volumes:
      - shard2-1:/data/db
    command:
      [
        "--shardsvr", 
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27018"
      ] 

  shard2-2:
    container_name: shard2-2
    image: dh-mirror.gitverse.ru/mongo:latest    
    ports:
      - "27023:27018"
    volumes:
      - shard2-2:/data/db
    command:
      [
        "--shardsvr", 
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27018"
      ] 

  shard2-3:
    container_name: shard2-3
    image: dh-mirror.gitverse.ru/mongo:latest    
    ports:
      - "27024:27018"
    volumes:
      - shard2-3:/data/db
    command:
      [
        "--shardsvr", 
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27018"
      ] 
  router:
    image: dh-mirror.gitverse.ru/mongo:latest    
    container_name: router
    ports:
      - "27020:27017"    
    command:
      [
        "mongos", 
        "-configdb", 
        "config_server/configSrv:27017",
        "--bind_ip_all",
        "--port",
        "27017"
      ]

  redis:
    image: "redis:latest"
    container_name: redis
    command: >
        sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&       
        redis-server /usr/local/etc/redis/redis.conf
        '
    

  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - configSrv
      - router
      - shard1-1
      - shard1-2
      - shard1-3
      - shard2-1
      - shard2-2
      - shard2-3
      - redis
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://router"
      MONGODB_DATABASE_NAME: "somedb"
      REDIS_URL: "redis://redis:6379"
  
     

volumes:
  config-data:
  shard1-1:
  shard1-2:
  shard1-3:
  shard2-1:  
  shard2-2:
  shard2-3: